### ISSUE TITLE
你好，数据库那怎么建，能不能说一下，我想学习一下？谢谢

### ISSUE THREAD

**Issue by nasasky** [dongxi346/doughnut#1]

**Comment by hjs557523** [comment]
请问这是单用户还是多用户呢？

**Comment by YGragon** [comment]
> 请问这是单用户还是多用户呢？

多用户的

**Comment by YGragon** [comment]
在 README 中有数据表，你下载下来运行后先提交数据，在云数据库后台中就可以看到数据表结构了

**Comment by hjs557523** [comment]
好的谢谢大神~


------------------ 原始邮件 ------------------
发件人: "Aller_Dong"<notifications@github.com>;
发送时间: 2019年6月2日(星期天) 晚上6:32
收件人: "dongxi346/doughnut"<doughnut@noreply.github.com>;
抄送: "16041321 黄继升"<326464623@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [dongxi346/doughnut] 你好，数据库那怎么建，能不能说一下，我想学习一下？谢谢 (#1)




在 README 中有数据表，你下载下来运行后先提交数据，在云数据库后台中就可以看到数据表结构了
