### ISSUE TITLE
你好，我想在collect中新增content但是数据库的content总是空的，希望可以指导一下，谢谢

### ISSUE THREAD

**Issue by xy97518** [dongxi346/doughnut#6]
getTextAreaContent: function (event) {
    that.data.content = event.detail.value;
  },

  saveToCollectServer: function (event) {
    db.collection('collect').add({
      // data 字段表示需新增的 JSON 数据
      data: {
        _id: that.data.id,
        date: new Date(),
        user: that.data.user,
        content: that.data.content ,
      },
      success:res=> {
        that.refreshLikeIcon(true)
        this.setData({ 
          content: event.detail.value
        })
        
      },
    })
  },

**Comment by YGragon** [comment]
看一下 that.data.content 是不是空的吧，还有检查 getTextAreaContent 方法是不是在 wxml 中定义的方法

**Comment by YGragon** [comment]
close
